name: Express.js Deployment
env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Deploy to Vercel
              run: |
                  # Log in to Vercel (replace with your Vercel token)
                  npx vercel login --token ${{ secrets.VERCEL_TOKEN }}

                  # Deploy the Express.js app to Vercel
                  npx vercel --prod
